#pragma once
#include<Source\Component\Component.h>
#include<Source\Component\Render2DComponent.h>
#include<Source\Component\Render3DComponent.h>
#include<Source\Component\RenderClientComponent.h>
#include<Source\Component\RenderOwnerComponent.h>
#include<Source\Component\SpriteRenderComponent.h>
#include<Source\Component\UpdateComponent.h>
#include<Source\Component\DebugTest\Test.h>
#include<Source\Component\CameraComponent.h>
#include<Source\Component\CameraContoroller.h>
#include<Source\Component\Effect\DirectionalLightComponent.h>
#include<Source\Component\DebugTest\DebugContoroller.h>
#include<Source\Component\Effect\PointLightComponent.h>
#include<Source\Component\BoxRenderClientComponent.h>
#include<Source\Component\DebugTest\DebugPointLightController.h>
#include<Source\Component\DebugTest\DebugParticl.h>
#include<Source\Component\Animation\AnimatorComponent.h>
#include<Source\Component\Player\PlayerComponent.h>
#include<Source\Component\Physics\BoxCollider.h>
#include<Source\Component\Physics\CircleCollider.h>
#include<Source\Component\Effect\BloomEffect.h>
#include<Source\Component\Device\CameraMove.h>
#include<Source\Component\Stage\StageMotion.h>
#include<Source\Component\Physics\RigidBody.h>
#include<Source\Component\Effect\BloomEffect.h>
#include<Source\Component\Scene\Title\TitleCharacter.h>
#include<Source\Component\Scene\Title\Buttom.h>
#include<Source\Component\Effect\BlurEffect.h>
#include<Source\Component\FadeComponent.h>
#include<Source\Component\Scene\GameMain\ReadyComponent.h>
#include<Source\Component\Scene\GameMain\RulesComponent.h>
#include<Source\Component\Scene\Result\RankSortComponent.h>
#include<Source\Component\Scene\Result\NextButton.h>